package com.jobtracker.dto.gdrive;

import io.swagger.v3.oas.annotations.media.Schema;

import java.util.List;

@Schema(description = "OAuth start response for Google Drive connection")
public record GoogleDriveOAuthStartResponse(
        @Schema(description = "Google OAuth authorization URL")
        String authorizationUrl,
        @Schema(description = "Opaque state generated by the backend")
        String state,
        @Schema(description = "Configured backend redirect URI")
        String redirectUri,
        @Schema(description = "OAuth scopes requested by the backend")
        List<String> scopes
) {}
